### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by HandaSei** [ArjixGamer/Nyaa-Utility#1]
How the title say, can u please make the extension also for firefox?

**Comment by ArjixWasTaken** [comment]
Hmm, I don't really want to bother making a firefox plug-in, I can give it a try but I most likely won't.
A PR would be welcome tho

**Comment by ArjixWasTaken** [comment]
actually you can load the extension in firefox just fine...
its just that it has to be loaded as a temporary add-on unless i publish it

you can
* go to about:debugging
* then do what the screenshot shows
![image](https://user-images.githubusercontent.com/53124886/111843146-580ead80-8909-11eb-9760-f3f8a064e5a1.png)
* after that select the manifest.json in the extensions folder

**Comment by ArjixWasTaken** [comment]
i did submit my addon on firefox, waiting to see if it will get rejected or accepted

**Comment by ArjixWasTaken** [comment]
done, its now available on firefox
