### ISSUE TITLE
File list in popup

### ISSUE THREAD

**Issue by oSumAtrIX** [ArjixGamer/Nyaa-Utility#13]
I was trying out the popup and liked the feature but I was missing this in the popup:
![image](https://user-images.githubusercontent.com/13122796/150707480-f0d5db73-4746-4d05-b6ff-36a728214175.png)

Maybe it could be added, the same way comments expand?

**Comment by ArjixWasTaken** [comment]
Sure I can add it
But I thought that a pop-up was just a preview of the torrent.

**Comment by oSumAtrIX** [comment]
Yeah, the file list is a preview of the contents of the torrents. Instead, the torrent & magnet button for example might be unnecessary as you can just use the buttons on the listing already
