### ISSUE TITLE
Block uploads from blocked users?

### ISSUE THREAD

**Issue by StarrryLight** [ArjixGamer/Nyaa-Utility#14]
I'm mainly asking for this, because sometimes (mainly with raw manga) the uploader won't use a tag, so it would be nice if there was a feature, where in, you could block torrents from blocked users from appearing on the front page, this isn't a major issue, but it would be a nice thing to have. Thanks.

**Comment by ArjixWasTaken** [comment]
well, as much as I would love to do that, if you look at the html for a torrent in the front page, you won't find a single thing that could tell you who uploaded the torrent

only way of blocking torrents from the front page would be by the tag names

**Comment by StarrryLight** [comment]
dang, that sucks, but I guess I'll live with it, it's still a vast improvement over regular nyaa, thanks for your hard work.

**Comment by ArjixWasTaken** [comment]
Actually the version you are using is the legacy one, some months ago I started work on the next major version, which is still a W.I.P. but I haven't done work on it for a long time.

So I am thinking of either remaking it from scratch, or to try and fix some issues with the beta.
