### ISSUE TITLE
Give documentation its own page

### ISSUE THREAD

**Issue by LightArrowsEXE** [ArjixGamer/Nyaa-Utility#3]
It took someone else to tell me that the basic documentation is in the Nyaa Info/help section. I think it would be a better idea to have this available on another page, potentially linked to in the same dropdown bar as on Nyaa.

Like for example here, as another option,
![image](https://user-images.githubusercontent.com/42927908/128648537-e07447c4-d23a-4eca-b5ea-f273cf794bd4.png)

This would make it much more self-evident and slightly easier to find. Could also have it automatically open this page when the extension is installed for the first time, as well as maybe link to it if you try to access the extension's setting.

If you can't magically create a page for it, it might be feasible to create a github environments page just for this and link users to that instead.

**Comment by ArjixWasTaken** [comment]
Nice idea!
I will do that in the next release.

PS: Please use the github issue tracker because I'm not a person that
checks my emails if I'm not expecting an email to come in the first place.

**Comment by ArjixWasTaken** [comment]
~~Ok, ignore my deleted message, I'm blind to obvious things.~~
Nice idea!
Will do so.

**Comment by ArjixWasTaken** [comment]
~~Hmm, then I will make a new link inside the nyaa info menu dropdown, how does that sound?~~
Once again I'm blind to obvious things...
that's what you said I should do...

Aight

**Comment by LightArrowsEXE** [comment]
It happens lol. I think that'd be the best place, although if you want to make it even more obvious, you can add it as an additional page next to `Fap` or something (also TIL you can see comment edits in realtime)

**Comment by ArjixWasTaken** [comment]
> (also TIL you can see comment edits in realtime)

I think it checks at a set interval for any changes.

**Comment by ArjixWasTaken** [comment]
> If you can't magically create a page for it, it might be feasible to create a github environments page just for this and link users to that instead.

That's not a problem, see https://nyaa.si/notifications and https://nyaa.si/settings

**Comment by ArjixWasTaken** [comment]
I really want to rewrite some stuff as well...
So it might take time for the next release to be out.

Current biggest problem is that all the scripts are loaded even if they are not needed.
Thats not a huge problem since the scripts are stored inside the extension,
but it is if you think that half of them will do nothing.

So for now I want to implement dynamic loading of the scripts.

**Comment by ArjixWasTaken** [comment]
Ok, this was faster than what I expected it to take.
Anyways, I'll close this issue but keep in mind that I won't push the new version until I fix a bug I found.

https://nyaa.si/nyaa-utility
