### ISSUE TITLE
Subscribing to threads is unreliable when multiple tabs are open

### ISSUE THREAD

**Issue by motbob** [ArjixGamer/Nyaa-Utility#7]
Firefox, 1.5

Over the last week, I tried to subscribe to a bunch of comment threads like so:

- Open a bunch of tabs
- Subscribe, move to the next tab, subscribe, etc.
- Close all the tabs at the end

This never resulted in logging the subscriptions that I was trying to do. I think this method only subscribes to the last tab in the series, but I could be wrong.

Today, I tried navigating to the thread I wanted to subscribe to, subscribing, and hitting the back button, without opening a new tab. That worked consistently.

**Comment by ArjixWasTaken** [comment]
~~Hmm, did you close the tabs too fast?
It's made to refresh the page when it actually saves correctly.~~
Oh, I get why it happened.
Will fix.

**Comment by ArjixWasTaken** [comment]
Ok, uhh, can you load the extension from github?

1. Clone the repository to a folder.
2. Follow the steps in the guide [here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on)

**Comment by motbob** [comment]
> 
> 
> Ok, uhh, can you load the extension from github?
> 
>     1. Clone the repository to a folder.
> 
>     2. Follow the steps in the guide [here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on)

I disabled the old add-on and then followed the instructions. It said it was version 1.6 on the help page, so I think I loaded the add-on correctly. However, the issue was not fixed. I tried the "multiple tabs" method and only ended up subscribed to the thread in the last tab.

**Comment by ArjixWasTaken** [comment]
> > Ok, uhh, can you load the extension from github?
> > ```
> > 1. Clone the repository to a folder.
> > 
> > 2. Follow the steps in the guide [here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on)
> > ```
> 
> I disabled the old add-on and then followed the instructions. It said it was version 1.6 on the help page, so I think I loaded the add-on correctly. However, the issue was not fixed. I tried the "multiple tabs" method and only ended up subscribed to the thread in the last tab.

Hmm...
Did the page refresh on its own before you closed the tab?

**Comment by motbob** [comment]
> 
> 
> > > Ok, uhh, can you load the extension from github?
> > > ```
> > > 1. Clone the repository to a folder.
> > > 
> > > 2. Follow the steps in the guide [here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on)
> > > ```
> > 
> > 
> > I disabled the old add-on and then followed the instructions. It said it was version 1.6 on the help page, so I think I loaded the add-on correctly. However, the issue was not fixed. I tried the "multiple tabs" method and only ended up subscribed to the thread in the last tab.
> 
> Hmm...
> Did the page refresh on its own before you closed the tab?

Yes, the page always refreshes quickly.

**Comment by ArjixWasTaken** [comment]
> > > > Ok, uhh, can you load the extension from github?
> > > > ```
> > > > 1. Clone the repository to a folder.
> > > > 
> > > > 2. Follow the steps in the guide [here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on)
> > > > ```
> > > 
> > > 
> > > I disabled the old add-on and then followed the instructions. It said it was version 1.6 on the help page, so I think I loaded the add-on correctly. However, the issue was not fixed. I tried the "multiple tabs" method and only ended up subscribed to the thread in the last tab.
> > 
> > 
> > Hmm...
> > Did the page refresh on its own before you closed the tab?
> 
> Yes, the page always refreshes quickly.

Welp, I guess I can't do anything about it then.
Currently I use the browser api to store settings.
And that is not so reliable if you modify settings too fast it seems. (it is asynchronous)

Just slow down, wait for like 2 seconds before following another torrent.

If you open the developer tools you will see that I print the current settings to the config
`subscribedThreads` contains the followed torrents
![image](https://user-images.githubusercontent.com/53124886/129982891-0254c561-05c9-4a0f-aa58-caa709618ba5.png)
in the above image I follow 1 torrent

**Comment by ArjixWasTaken** [comment]
Oh, since you use "threads" in the issue's title I guess you knew about the console message?

**Comment by motbob** [comment]
I did more tests, and this doesn't have anything to do with subscribing too fast.

- Open two tabs with two threads you want to subscribe to.
- Subscribe to the first tab. Wait a bit, refresh, whatever. You'll stay subscribed.
- Subscribe to the second one. Tab back to the first thread, refresh. Bam, you're unsubscribed.

The issue is that subscribing to subsequent tabs erases the previous subscriptions for whatever reason.

**Comment by ArjixWasTaken** [comment]
Oh, I get why.
It's because the data get's overwritten.
If you refresh the 2nd tab before subscribing it should work fine.
I can fix that.

**Comment by ArjixWasTaken** [comment]
Retry now with the latest data.

**Comment by ArjixWasTaken** [comment]
actually no, wait a min

**Comment by ArjixWasTaken** [comment]
ok, now

**Comment by ArjixWasTaken** [comment]
Ok I promise this is the last time, finally fixed it

**Comment by ArjixWasTaken** [comment]
Uhh...it semi works i guess

**Comment by ArjixWasTaken** [comment]
;-;

**Comment by motbob** [comment]
Appears to work now. I'm having no problems in Firefox.

**Comment by ArjixWasTaken** [comment]
welp
its not entirely fixed (if you try hard enough it will do the same thing as before), but I really can't improve it more than this.
(unsubscribing on a previous tab removes any new subscription)

**Comment by ArjixWasTaken** [comment]
Let's leave it at that.

**Comment by ArjixWasTaken** [comment]
(This is completely fixed in the rewrite)

But the rewrite is still a W.I.P. so don't use it.
